//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InnogrityLinePackingClient.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-4")]
        public double lblXmin2 {
            get {
                return ((double)(this["lblXmin2"]));
            }
            set {
                this["lblXmin2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public double lblXmax2 {
            get {
                return ((double)(this["lblXmax2"]));
            }
            set {
                this["lblXmax2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-4")]
        public double lblYmin2 {
            get {
                return ((double)(this["lblYmin2"]));
            }
            set {
                this["lblYmin2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public double lblYmax2 {
            get {
                return ((double)(this["lblYmax2"]));
            }
            set {
                this["lblYmax2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-3")]
        public double lblDegmin2 {
            get {
                return ((double)(this["lblDegmin2"]));
            }
            set {
                this["lblDegmin2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public double lblDegmax2 {
            get {
                return ((double)(this["lblDegmax2"]));
            }
            set {
                this["lblDegmax2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.14")]
        public double printTopmin2 {
            get {
                return ((double)(this["printTopmin2"]));
            }
            set {
                this["printTopmin2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("99999")]
        public double printTopmax2 {
            get {
                return ((double)(this["printTopmax2"]));
            }
            set {
                this["printTopmax2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.14")]
        public double printBtmmin2 {
            get {
                return ((double)(this["printBtmmin2"]));
            }
            set {
                this["printBtmmin2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("99999")]
        public double printBtmmax2 {
            get {
                return ((double)(this["printBtmmax2"]));
            }
            set {
                this["printBtmmax2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.14")]
        public double printLefmin2 {
            get {
                return ((double)(this["printLefmin2"]));
            }
            set {
                this["printLefmin2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("99999")]
        public double printLefmax2 {
            get {
                return ((double)(this["printLefmax2"]));
            }
            set {
                this["printLefmax2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.14")]
        public double printRitemin2 {
            get {
                return ((double)(this["printRitemin2"]));
            }
            set {
                this["printRitemin2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("99999")]
        public double printRitemax2 {
            get {
                return ((double)(this["printRitemax2"]));
            }
            set {
                this["printRitemax2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double SpekTopmin2 {
            get {
                return ((double)(this["SpekTopmin2"]));
            }
            set {
                this["SpekTopmin2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("99999")]
        public double SpekTopmax2 {
            get {
                return ((double)(this["SpekTopmax2"]));
            }
            set {
                this["SpekTopmax2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double SpekBtmmin2 {
            get {
                return ((double)(this["SpekBtmmin2"]));
            }
            set {
                this["SpekBtmmin2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("99999")]
        public double SpekBtmmax2 {
            get {
                return ((double)(this["SpekBtmmax2"]));
            }
            set {
                this["SpekBtmmax2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double SpekLefmin2 {
            get {
                return ((double)(this["SpekLefmin2"]));
            }
            set {
                this["SpekLefmin2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("99999")]
        public double SpekLefmax2 {
            get {
                return ((double)(this["SpekLefmax2"]));
            }
            set {
                this["SpekLefmax2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double SpekRitemin2 {
            get {
                return ((double)(this["SpekRitemin2"]));
            }
            set {
                this["SpekRitemin2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("99999")]
        public double SpekRitemax2 {
            get {
                return ((double)(this["SpekRitemax2"]));
            }
            set {
                this["SpekRitemax2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double IntTopmin2 {
            get {
                return ((double)(this["IntTopmin2"]));
            }
            set {
                this["IntTopmin2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("99999")]
        public double IntTopmax2 {
            get {
                return ((double)(this["IntTopmax2"]));
            }
            set {
                this["IntTopmax2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double IntBtmmin2 {
            get {
                return ((double)(this["IntBtmmin2"]));
            }
            set {
                this["IntBtmmin2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("99999")]
        public double IntBtmmax2 {
            get {
                return ((double)(this["IntBtmmax2"]));
            }
            set {
                this["IntBtmmax2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double IntLefmin2 {
            get {
                return ((double)(this["IntLefmin2"]));
            }
            set {
                this["IntLefmin2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("99999")]
        public double IntLefmax2 {
            get {
                return ((double)(this["IntLefmax2"]));
            }
            set {
                this["IntLefmax2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double IntRitemin2 {
            get {
                return ((double)(this["IntRitemin2"]));
            }
            set {
                this["IntRitemin2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("99999")]
        public double IntRitemax2 {
            get {
                return ((double)(this["IntRitemax2"]));
            }
            set {
                this["IntRitemax2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-4")]
        public double lblXmin4 {
            get {
                return ((double)(this["lblXmin4"]));
            }
            set {
                this["lblXmin4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public double lblXmax4 {
            get {
                return ((double)(this["lblXmax4"]));
            }
            set {
                this["lblXmax4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-4")]
        public double lblYmin4 {
            get {
                return ((double)(this["lblYmin4"]));
            }
            set {
                this["lblYmin4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public double lblYmax4 {
            get {
                return ((double)(this["lblYmax4"]));
            }
            set {
                this["lblYmax4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-3")]
        public double lblDegmin4 {
            get {
                return ((double)(this["lblDegmin4"]));
            }
            set {
                this["lblDegmin4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public double lblDegmax4 {
            get {
                return ((double)(this["lblDegmax4"]));
            }
            set {
                this["lblDegmax4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.14")]
        public double printTopmin4 {
            get {
                return ((double)(this["printTopmin4"]));
            }
            set {
                this["printTopmin4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("99999")]
        public double printTopmax4 {
            get {
                return ((double)(this["printTopmax4"]));
            }
            set {
                this["printTopmax4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.14")]
        public double printBtmmin4 {
            get {
                return ((double)(this["printBtmmin4"]));
            }
            set {
                this["printBtmmin4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("99999")]
        public double printBtmmax4 {
            get {
                return ((double)(this["printBtmmax4"]));
            }
            set {
                this["printBtmmax4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.14")]
        public double printLefmin4 {
            get {
                return ((double)(this["printLefmin4"]));
            }
            set {
                this["printLefmin4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("99999")]
        public double printLefmax4 {
            get {
                return ((double)(this["printLefmax4"]));
            }
            set {
                this["printLefmax4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.14")]
        public double printRitemin4 {
            get {
                return ((double)(this["printRitemin4"]));
            }
            set {
                this["printRitemin4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("99999")]
        public double printRitemax4 {
            get {
                return ((double)(this["printRitemax4"]));
            }
            set {
                this["printRitemax4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double SpekTopmin4 {
            get {
                return ((double)(this["SpekTopmin4"]));
            }
            set {
                this["SpekTopmin4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("99999")]
        public double SpekTopmax4 {
            get {
                return ((double)(this["SpekTopmax4"]));
            }
            set {
                this["SpekTopmax4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double SpekBtmmin4 {
            get {
                return ((double)(this["SpekBtmmin4"]));
            }
            set {
                this["SpekBtmmin4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("99999")]
        public double SpekBtmmax4 {
            get {
                return ((double)(this["SpekBtmmax4"]));
            }
            set {
                this["SpekBtmmax4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double SpekLefmin4 {
            get {
                return ((double)(this["SpekLefmin4"]));
            }
            set {
                this["SpekLefmin4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("99999")]
        public double SpekLefmax4 {
            get {
                return ((double)(this["SpekLefmax4"]));
            }
            set {
                this["SpekLefmax4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double SpekRitemin4 {
            get {
                return ((double)(this["SpekRitemin4"]));
            }
            set {
                this["SpekRitemin4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("99999")]
        public double SpekRitemax4 {
            get {
                return ((double)(this["SpekRitemax4"]));
            }
            set {
                this["SpekRitemax4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double IntTopmin4 {
            get {
                return ((double)(this["IntTopmin4"]));
            }
            set {
                this["IntTopmin4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("99999")]
        public double IntTopmax4 {
            get {
                return ((double)(this["IntTopmax4"]));
            }
            set {
                this["IntTopmax4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double IntBtmmin4 {
            get {
                return ((double)(this["IntBtmmin4"]));
            }
            set {
                this["IntBtmmin4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("99999")]
        public double IntBtmmax4 {
            get {
                return ((double)(this["IntBtmmax4"]));
            }
            set {
                this["IntBtmmax4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double IntLefmin4 {
            get {
                return ((double)(this["IntLefmin4"]));
            }
            set {
                this["IntLefmin4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("99999")]
        public double IntLefmax4 {
            get {
                return ((double)(this["IntLefmax4"]));
            }
            set {
                this["IntLefmax4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double IntRitemin4 {
            get {
                return ((double)(this["IntRitemin4"]));
            }
            set {
                this["IntRitemin4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("99999")]
        public double IntRitemax4 {
            get {
                return ((double)(this["IntRitemax4"]));
            }
            set {
                this["IntRitemax4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-4")]
        public double lblXmin7 {
            get {
                return ((double)(this["lblXmin7"]));
            }
            set {
                this["lblXmin7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public double lblXmax7 {
            get {
                return ((double)(this["lblXmax7"]));
            }
            set {
                this["lblXmax7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-4")]
        public double lblYmin7 {
            get {
                return ((double)(this["lblYmin7"]));
            }
            set {
                this["lblYmin7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public double lblYmax7 {
            get {
                return ((double)(this["lblYmax7"]));
            }
            set {
                this["lblYmax7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-3")]
        public double lblDegmin7 {
            get {
                return ((double)(this["lblDegmin7"]));
            }
            set {
                this["lblDegmin7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public double lblDegmax7 {
            get {
                return ((double)(this["lblDegmax7"]));
            }
            set {
                this["lblDegmax7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.14")]
        public double printTopmin7 {
            get {
                return ((double)(this["printTopmin7"]));
            }
            set {
                this["printTopmin7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("99999")]
        public double printTopmax7 {
            get {
                return ((double)(this["printTopmax7"]));
            }
            set {
                this["printTopmax7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.14")]
        public double printBtmmin7 {
            get {
                return ((double)(this["printBtmmin7"]));
            }
            set {
                this["printBtmmin7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("99999")]
        public double printBtmmax7 {
            get {
                return ((double)(this["printBtmmax7"]));
            }
            set {
                this["printBtmmax7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.14")]
        public double printLefmin7 {
            get {
                return ((double)(this["printLefmin7"]));
            }
            set {
                this["printLefmin7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("99999")]
        public double printLefmax7 {
            get {
                return ((double)(this["printLefmax7"]));
            }
            set {
                this["printLefmax7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.14")]
        public double printRitemin7 {
            get {
                return ((double)(this["printRitemin7"]));
            }
            set {
                this["printRitemin7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("99999")]
        public double printRitemax7 {
            get {
                return ((double)(this["printRitemax7"]));
            }
            set {
                this["printRitemax7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-4")]
        public double lblXmin7a {
            get {
                return ((double)(this["lblXmin7a"]));
            }
            set {
                this["lblXmin7a"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public double lblXmax7a {
            get {
                return ((double)(this["lblXmax7a"]));
            }
            set {
                this["lblXmax7a"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-4")]
        public double lblYmin7a {
            get {
                return ((double)(this["lblYmin7a"]));
            }
            set {
                this["lblYmin7a"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public double lblYmax7a {
            get {
                return ((double)(this["lblYmax7a"]));
            }
            set {
                this["lblYmax7a"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-3")]
        public double lblDegmin7a {
            get {
                return ((double)(this["lblDegmin7a"]));
            }
            set {
                this["lblDegmin7a"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public double lblDegmax7a {
            get {
                return ((double)(this["lblDegmax7a"]));
            }
            set {
                this["lblDegmax7a"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.14")]
        public double printTopmin7a {
            get {
                return ((double)(this["printTopmin7a"]));
            }
            set {
                this["printTopmin7a"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("99999")]
        public double printTopmax7a {
            get {
                return ((double)(this["printTopmax7a"]));
            }
            set {
                this["printTopmax7a"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.14")]
        public double printBtmmin7a {
            get {
                return ((double)(this["printBtmmin7a"]));
            }
            set {
                this["printBtmmin7a"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("99999")]
        public double printBtmmax7a {
            get {
                return ((double)(this["printBtmmax7a"]));
            }
            set {
                this["printBtmmax7a"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.14")]
        public double printLefmin7a {
            get {
                return ((double)(this["printLefmin7a"]));
            }
            set {
                this["printLefmin7a"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("99999")]
        public double printLefmax7a {
            get {
                return ((double)(this["printLefmax7a"]));
            }
            set {
                this["printLefmax7a"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.14")]
        public double printRitemin7a {
            get {
                return ((double)(this["printRitemin7a"]));
            }
            set {
                this["printRitemin7a"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("99999")]
        public double printRitemax7a {
            get {
                return ((double)(this["printRitemax7a"]));
            }
            set {
                this["printRitemax7a"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double SpekTopmin7 {
            get {
                return ((double)(this["SpekTopmin7"]));
            }
            set {
                this["SpekTopmin7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("99999")]
        public double SpekTopmax7 {
            get {
                return ((double)(this["SpekTopmax7"]));
            }
            set {
                this["SpekTopmax7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double SpekBtmmin7 {
            get {
                return ((double)(this["SpekBtmmin7"]));
            }
            set {
                this["SpekBtmmin7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("99999")]
        public double SpekBtmmax7 {
            get {
                return ((double)(this["SpekBtmmax7"]));
            }
            set {
                this["SpekBtmmax7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double SpekLefmin7 {
            get {
                return ((double)(this["SpekLefmin7"]));
            }
            set {
                this["SpekLefmin7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("99999")]
        public double SpekLefmax7 {
            get {
                return ((double)(this["SpekLefmax7"]));
            }
            set {
                this["SpekLefmax7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double SpekRitemin7 {
            get {
                return ((double)(this["SpekRitemin7"]));
            }
            set {
                this["SpekRitemin7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("99999")]
        public double SpekRitemax7 {
            get {
                return ((double)(this["SpekRitemax7"]));
            }
            set {
                this["SpekRitemax7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double IntTopmin7 {
            get {
                return ((double)(this["IntTopmin7"]));
            }
            set {
                this["IntTopmin7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("99999")]
        public double IntTopmax7 {
            get {
                return ((double)(this["IntTopmax7"]));
            }
            set {
                this["IntTopmax7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double IntBtmmin7 {
            get {
                return ((double)(this["IntBtmmin7"]));
            }
            set {
                this["IntBtmmin7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("99999")]
        public double IntBtmmax7 {
            get {
                return ((double)(this["IntBtmmax7"]));
            }
            set {
                this["IntBtmmax7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double IntLefmin7 {
            get {
                return ((double)(this["IntLefmin7"]));
            }
            set {
                this["IntLefmin7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("99999")]
        public double IntLefmax7 {
            get {
                return ((double)(this["IntLefmax7"]));
            }
            set {
                this["IntLefmax7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double IntRitemin7 {
            get {
                return ((double)(this["IntRitemin7"]));
            }
            set {
                this["IntRitemin7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("99999")]
        public double IntRitemax7 {
            get {
                return ((double)(this["IntRitemax7"]));
            }
            set {
                this["IntRitemax7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("175")]
        public double SpekDegmin4 {
            get {
                return ((double)(this["SpekDegmin4"]));
            }
            set {
                this["SpekDegmin4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("185")]
        public double SpekDegmax4 {
            get {
                return ((double)(this["SpekDegmax4"]));
            }
            set {
                this["SpekDegmax4"] = value;
            }
        }
    }
}
